# Game settings
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 640
GAME_NAME = "Rambinho: O Último Soldado"
FPS = 60

SCROLLING_THRESHOLD = 500

# Bullet
DISTANCE_FROM_PLAYER = 48
Y_AXIS_BULLET = 16

# Player
PLAYER_SPEED = 5
PLAYER_HP = 6

# ENEMY
ENEMY_HP = 4
ENEMY_SPEED = 3
AI_DECISION_COOLDOWN = 500 # ms

WOLRD_CSV_ROWS = 16
WOLRD_CSV_COLLUNMS = 150
TILE_SIZE = SCREEN_HEIGHT // WOLRD_CSV_ROWS
TILE_TYPES = 21

FLOOR_Y = SCREEN_HEIGHT - 128

BOSS_MAX_HP = 10